import type { ApiColumn, ApiRow, ApiSectionData } from './shared/ComponentApiDocs';
const columns: ApiColumn[] = [{ key: 'name', label: '이름' }, { key: 'description', label: '설명' }, { key: 'default', label: '기본값' }, { key: 'type', label: '타입' }];
const section = (title: string, rows: ApiRow[]): ApiSectionData => ({ title, tables: [{ columns, rows }] });
export const breadcrumbApiSections: ApiSectionData[] = [
  section('Breadcrumb API', [{ name: 'items', type: 'BreadcrumbItemData[]', default: '[]', description: '데이터 기반 경로 항목입니다. 마지막 항목은 기본적으로 현재 위치가 됩니다.' }, { name: 'ariaLabel', type: 'string', default: "'경로'", description: '경로 내비게이션의 접근 가능한 이름입니다.' }, { name: 'separator', type: "'chevron' | 'slash' | 'dot'", default: "'chevron'", description: '항목 사이 구분자입니다.' }, { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Breadcrumb 텍스트 크기입니다.' }, { name: 'children · default slot', type: 'ReactNode · slot', default: '—', description: 'BreadcrumbItem을 직접 조합하는 영역입니다.' }]),
  section('BreadcrumbItem API', [{ name: 'label · children · default slot', type: 'string · ReactNode · slot', default: '—', description: '항목 텍스트 또는 아이콘을 포함한 커스텀 콘텐츠입니다.' }, { name: 'href', type: 'string', default: '—', description: '이전 경로의 링크입니다.' }, { name: 'current', type: 'boolean', default: 'false', description: '현재 페이지이며 aria-current="page"를 적용합니다.' }, { name: 'disabled', type: 'boolean', default: 'false', description: '이동할 수 없는 경로 상태입니다.' }, { name: 'icon', type: 'boolean · ReactNode', default: 'false', description: '아이콘 전용 링크 스타일 또는 React 아이콘 콘텐츠입니다.' }, { name: 'ariaLabel', type: 'string', default: '—', description: '아이콘 전용 링크의 접근 가능한 이름입니다.' }]),
  section('BreadcrumbEllipsis API', [{ name: 'expanded', type: 'boolean', default: 'false', description: '숨겨진 경로가 펼쳐졌는지 나타냅니다.' }, { name: 'label', type: 'string', default: "'숨겨진 경로 보기'", description: '생략 버튼의 접근 가능한 이름입니다.' }, { name: 'onClick · @click', type: 'handler', default: '—', description: '숨겨진 경로 표시 상태를 전환합니다.' }]),
  section('HTML · Gulp', [{ name: 'breadcrumb_list · breadcrumb_item', type: 'class', default: '—', description: '순서가 있는 경로 목록 구조입니다.' }, { name: 'breadcrumb_link · breadcrumb_current', type: 'class', default: '—', description: '이전 경로 링크와 현재 위치입니다.' }, { name: 'breadcrumb_ellipsis · data-breadcrumb-hidden', type: 'class · attribute', default: '—', description: '긴 경로의 생략 버튼과 숨김 항목입니다.' }]),
  section('디자인 토큰', [{ name: '--breadcrumb-font-size', type: 'length', default: 'text-size-sm', description: '기본 글자 크기입니다.' }, { name: '--breadcrumb-gap · --breadcrumb-icon-gap', type: 'length', default: 'space-xs · 0.25rem', description: '항목 및 아이콘 간격입니다.' }, { name: '--breadcrumb-link-max-width', type: 'length', default: '12rem', description: '긴 항목이 말줄임되는 최대 너비입니다.' }]),
];
