import type { FrameworkExample } from './FrameworkCode';

function examples(component: 'Table' | 'List' | 'Stat', slug: string, key: string, html: string, reactBody: string, vueBody: string): FrameworkExample[] {
  const companion = component === 'List' ? ', ListItem' : '';
  const react = `import { ${component}${companion} } from '@uxkm/react/${slug}';\n\nexport function Example() {\n  return (\n${reactBody}\n  );\n}`;
  const vue = `<script setup>\nimport { ${component}${companion} } from '@uxkm/vue/${slug}';\n</script>\n\n<template>\n${vueBody}\n</template>`;
  return [
    { id: 'html', label: 'HTML', fileName: `apps/html/src/components/data-display/${component}/${component}.html · ${key}`, code: html },
    { id: 'gulp', label: 'Gulp', fileName: `apps/gulp/src/components/data-display/${component}/${slug}.njk · ${key}`, code: `{# ${component} · ${key} #}\n${html}` },
    { id: 'vue', label: 'Vue', fileName: `@uxkm/vue/${slug} · ${key}`, code: vue },
    { id: 'nuxt', label: 'Nuxt', fileName: `@uxkm/vue/${slug} · ${key}`, code: vue },
    { id: 'react', label: 'React', fileName: `@uxkm/react/${slug} · ${key}`, code: react },
    { id: 'next', label: 'Next', fileName: `@uxkm/react/${slug} · ${key}`, code: react }
  ];
}

const tableMarkup = (classes = 'table') => `<div class="table_wrap">\n  <table class="${classes}">\n    <thead><tr><th scope="col">이름</th><th scope="col">직군</th><th scope="col">상태</th></tr></thead>\n    <tbody>\n      <tr><td>홍길동</td><td>Frontend</td><td>활성</td></tr>\n      <tr><td>김철수</td><td>Backend</td><td>활성</td></tr>\n      <tr><td>이영희</td><td>Design</td><td>휴가</td></tr>\n    </tbody>\n  </table>\n</div>`;
const tableBody = `      <thead><tr><th scope="col">이름</th><th scope="col">직군</th><th scope="col">상태</th></tr></thead>\n      <tbody><tr><td>홍길동</td><td>Frontend</td><td>활성</td></tr><tr><td>김철수</td><td>Backend</td><td>활성</td></tr></tbody>`;
const tableExample = (key: string, prop = '', classes = 'table', wrapper = 'table_wrap', vueProp = prop) => examples(
  'Table', 'table', key,
  tableMarkup(classes).replace('class="table_wrap"', `class="${wrapper}"`),
  `    <Table${prop ? ` ${prop}` : ''}>\n${tableBody}\n    </Table>`,
  `  <Table${vueProp ? ` ${vueProp}` : ''}>\n${tableBody.replace(/className=/g, 'class=')}\n  </Table>`
);

export const tableFrameworkExamples = {
  basic: tableExample('basic', `columns={[{ width: '9rem', nowrap: true }, { minWidth: '10rem' }, { width: '7rem' }]}`, 'table', 'table_wrap', `:columns="[{ width: '9rem', nowrap: true }, { minWidth: '10rem' }, { width: '7rem' }]"`),
  striped: tableExample('striped', 'striped', 'table table_striped'),
  bordered: tableExample('bordered', 'bordered', 'table table_bordered'),
  compact: tableExample('compact', 'compact', 'table table_compact'),
  hover: tableExample('hover', 'hover', 'table table_hover'),
  combined: tableExample('combined', 'bordered compact hover', 'table table_bordered table_compact table_hover'),
  stickyTop: tableExample('stickyTop', 'scroll scrollMaxHeight="14rem" stickyTop bordered compact', 'table table_sticky-top table_bordered table_compact', 'table_wrap table_wrap-scroll'),
  stickyLeft: tableExample('stickyLeft', 'scroll stickyLeft columns={columns}', 'table table_columns table_sticky-left table_sticky-cols-1', 'table_wrap table_wrap-scroll', 'scroll sticky-left :columns="columns"'),
  stickyColumns: tableExample('stickyColumns', 'scroll stickyLeft stickyCols={2} stickyLeftOffsets={{ 2: \'8rem\' }} columns={columns}', 'table table_columns table_sticky-left table_sticky-cols-2', 'table_wrap table_wrap-scroll', 'scroll sticky-left :sticky-cols="2" :sticky-left-offsets="{ 2: \'8rem\' }" :columns="columns"'),
  stickyBoth: tableExample('stickyBoth', 'scroll stickyTop stickyLeft stickyCols={2} stickyLeftOffsets={{ 2: \'8rem\' }} bordered compact', 'table table_bordered table_compact table_sticky-top table_sticky-left table_sticky-cols-2', 'table_wrap table_wrap-scroll', 'scroll sticky-top sticky-left :sticky-cols="2" :sticky-left-offsets="{ 2: \'8rem\' }" bordered compact')
};

const list = (key: string, html: string, react: string, vue: string) => examples('List', 'list', key, html, react, vue);
export const listFrameworkExamples = {
  basic: list('basic', `<ul class="list"><li class="list_item"><span class="avatar color_primary" aria-hidden="true">홍</span><div class="list_content"><span class="list_title">홍길동</span><span class="list_meta">프론트엔드 개발자</span></div></li></ul>`, `    <List><ListItem title="홍길동" meta="프론트엔드 개발자" prefix={<span className="avatar color_primary">홍</span>} /></List>`, `  <List><ListItem title="홍길동" meta="프론트엔드 개발자"><template #prefix><span class="avatar color_primary">홍</span></template></ListItem></List>`),
  bullet: list('bullet', `<ul class="list list_bullet"><li class="list_item">디자인 토큰 정의</li><li class="list_item">컴포넌트 문서화</li><li class="list_item">접근성 검토</li></ul>`, `    <List variant="bullet"><ListItem>디자인 토큰 정의</ListItem><ListItem>컴포넌트 문서화</ListItem><ListItem>접근성 검토</ListItem></List>`, `  <List variant="bullet"><ListItem>디자인 토큰 정의</ListItem><ListItem>컴포넌트 문서화</ListItem><ListItem>접근성 검토</ListItem></List>`),
  bulletRich: list('bulletRich', `<ul class="list list_bullet"><li class="list_item"><div class="list_content"><span class="list_title">HTML 마크업</span><span class="list_desc">시맨틱 태그와 ARIA 속성을 사용합니다.</span></div></li></ul>`, `    <List variant="bullet"><ListItem title="HTML 마크업" description="시맨틱 태그와 ARIA 속성을 사용합니다." /></List>`, `  <List variant="bullet"><ListItem title="HTML 마크업" description="시맨틱 태그와 ARIA 속성을 사용합니다." /></List>`),
  bulletVariants: list('bulletVariants', `<ul class="list list_bullet list_bullet-circle"><li class="list_item">원형 마커</li></ul>\n<ul class="list list_bullet list_bullet-square"><li class="list_item">사각 마커</li></ul>`, `    <><List variant="bullet" className="list_bullet-circle"><ListItem>원형 마커</ListItem></List><List variant="bullet" className="list_bullet-square"><ListItem>사각 마커</ListItem></List></>`, `  <List variant="bullet" class="list_bullet-circle"><ListItem>원형 마커</ListItem></List>\n  <List variant="bullet" class="list_bullet-square"><ListItem>사각 마커</ListItem></List>`),
  ordered: list('ordered', `<ol class="list list_ordered"><li class="list_item">요구사항 분석</li><li class="list_item">와이어프레임 작성</li><li class="list_item">개발 및 배포</li></ol>`, `    <List variant="ordered"><ListItem>요구사항 분석</ListItem><ListItem>와이어프레임 작성</ListItem><ListItem>개발 및 배포</ListItem></List>`, `  <List variant="ordered"><ListItem>요구사항 분석</ListItem><ListItem>와이어프레임 작성</ListItem><ListItem>개발 및 배포</ListItem></List>`),
  orderedVariants: list('orderedVariants', `<ol class="list list_ordered list_ordered-alpha"><li class="list_item">첫 번째 옵션</li></ol>\n<ol class="list list_ordered list_ordered-roman"><li class="list_item">서론</li></ol>`, `    <><List variant="ordered" className="list_ordered-alpha"><ListItem>첫 번째 옵션</ListItem></List><List variant="ordered" className="list_ordered-roman"><ListItem>서론</ListItem></List></>`, `  <List variant="ordered" class="list_ordered-alpha"><ListItem>첫 번째 옵션</ListItem></List>\n  <List variant="ordered" class="list_ordered-roman"><ListItem>서론</ListItem></List>`),
  hierarchical: list('hierarchical', `<ol class="list list_ordered list_ordered-outline"><li class="list_item">요구사항 정의</li><li class="list_item">설계<ol class="list list_ordered list_ordered-outline"><li class="list_item">정보 구조</li></ol></li></ol>`, `    <List variant="ordered" className="list_ordered-outline"><ListItem>요구사항 정의</ListItem><ListItem>설계<List variant="ordered" className="list_ordered-outline"><ListItem>정보 구조</ListItem></List></ListItem></List>`, `  <List variant="ordered" class="list_ordered-outline"><ListItem>요구사항 정의</ListItem><ListItem>설계<List variant="ordered" class="list_ordered-outline"><ListItem>정보 구조</ListItem></List></ListItem></List>`),
  bordered: list('bordered', `<ul class="list list_bordered"><li class="list_item"><div class="list_content"><span class="list_title">알림 설정</span><span class="list_desc">이메일 및 푸시 알림을 관리합니다.</span></div></li></ul>`, `    <List bordered><ListItem title="알림 설정" description="이메일 및 푸시 알림을 관리합니다." /></List>`, `  <List bordered><ListItem title="알림 설정" description="이메일 및 푸시 알림을 관리합니다." /></List>`),
  links: list('links', `<ul class="list list_divider"><li class="list_item"><a class="list_link" href="#" data-ripple="true"><span class="list_title">프로젝트</span></a></li></ul>`, `    <List split><ListItem><a className="list_link" href="#" data-ripple="true">프로젝트</a></ListItem></List>`, `  <List split><ListItem><a class="list_link" href="#" data-ripple="true">프로젝트</a></ListItem></List>`),
  buttons: list('buttons', `<ul class="list list_bordered"><li class="list_item"><button class="list_link" type="button" data-ripple="true">멤버 선택</button></li></ul>`, `    <List bordered><ListItem><button className="list_link" type="button" data-ripple="true">멤버 선택</button></ListItem></List>`, `  <List bordered><ListItem><button class="list_link" type="button" data-ripple="true">멤버 선택</button></ListItem></List>`),
  actions: list('actions', `<ul class="list list_bordered"><li class="list_item"><div class="list_content"><span class="list_title">디자인 시스템</span><span class="list_desc">마지막 수정 2시간 전</span></div><span class="list_action"><button type="button">열기</button></span></li></ul>`, `    <List bordered><ListItem title="디자인 시스템" description="마지막 수정 2시간 전" actions={<button type="button">열기</button>} /></List>`, `  <List bordered><ListItem title="디자인 시스템" description="마지막 수정 2시간 전"><template #actions><button type="button">열기</button></template></ListItem></List>`),
  definition: list('definition', `<dl class="list list_definition"><dt class="list_title">OOCSS</dt><dd class="list_desc">구조와 스킨을 분리하는 CSS 방법론</dd></dl>`, `    <List variant="definition"><ListItem title="OOCSS" description="구조와 스킨을 분리하는 CSS 방법론" /></List>`, `  <List variant="definition"><ListItem title="OOCSS" description="구조와 스킨을 분리하는 CSS 방법론" /></List>`),
  definitionInline: list('definitionInline', `<dl class="list list_definition list_inline"><dt class="list_title">OOCSS</dt><dd class="list_desc">구조와 스킨 분리</dd></dl>`, `    <List variant="definition" layout="inline" inlineLabelWidth="8rem"><ListItem title="OOCSS" description="구조와 스킨 분리" /></List>`, `  <List variant="definition" layout="inline" inline-label-width="8rem"><ListItem title="OOCSS" description="구조와 스킨 분리" /></List>`),
  definitionRight: list('definitionRight', `<dl class="list list_definition list_inline list_block list_desc-right"><dt class="list_title">결제금액</dt><dd class="list_desc">₩42,000</dd></dl>`, `    <List variant="definition" layout="inline" descAlign="right" block><ListItem title="결제금액" description="₩42,000" /></List>`, `  <List variant="definition" layout="inline" desc-align="right" block><ListItem title="결제금액" description="₩42,000" /></List>`)
};

const stat = (key: string, html: string, react: string, vue: string) => examples('Stat', 'stat', key, html, react, vue);
export const statFrameworkExamples = {
  basic: stat('basic', `<div class="stat"><span class="stat_label">총 사용자</span><span class="stat_value">12,480</span><span class="stat_desc">지난 30일 기준</span></div>`, `    <Stat title="총 사용자" value="12,480" description="지난 30일 기준" />`, `  <Stat title="총 사용자" value="12,480" description="지난 30일 기준" />`),
  prefixSuffix: stat('prefixSuffix', `<div class="stat"><span class="stat_label">총 매출</span><div class="stat_value-row"><span class="stat_prefix">₩</span><span class="stat_value">4,280,000</span></div><span class="stat_desc color_success">+8.2%</span></div>`, `    <Stat title="총 매출" prefix="₩" value="4,280,000" description="+8.2%" trendColor="success" />`, `  <Stat title="총 매출" prefix="₩" value="4,280,000" description="+8.2%" trend-color="success" />`),
  trend: stat('trend', `<div class="stat"><div class="stat_header"><span class="stat_label">신규 가입</span><span class="stat_trend color_success">↑ +15.3%</span></div><span class="stat_value">1,234</span></div>`, `    <Stat title="신규 가입" value="1,234" trend="+15.3%" trendColor="success" />`, `  <Stat title="신규 가입" value="1,234" trend="+15.3%" trend-color="success" />`),
  sizes: stat('sizes', `<div class="stat_group stat_group-3"><div class="stat stat_sm stat_card"><span class="stat_label">Small</span><span class="stat_value">1,024</span></div><div class="stat stat_card"><span class="stat_label">Medium</span><span class="stat_value">8,192</span></div><div class="stat stat_lg stat_card"><span class="stat_label">Large</span><span class="stat_value">64K</span></div></div>`, `    <div className="stat_group stat_group-3"><Stat size="sm" card title="Small" value="1,024" /><Stat card title="Medium" value="8,192" /><Stat size="lg" card title="Large" value="64K" /></div>`, `  <div class="stat_group stat_group-3"><Stat size="sm" card title="Small" value="1,024" /><Stat card title="Medium" value="8,192" /><Stat size="lg" card title="Large" value="64K" /></div>`),
  layouts: stat('layouts', `<div class="stat stat_horizontal stat_card"><span class="stat_label">활성 세션</span><span class="stat_value">342</span></div>`, `    <Stat className="stat_horizontal" card title="활성 세션" value="342" />`, `  <Stat class="stat_horizontal" card title="활성 세션" value="342" />`),
  icon: stat('icon', `<div class="stat stat_row stat_card"><span class="stat_icon-wrap color_success">✓</span><div class="stat_body"><span class="stat_label">완료</span><span class="stat_value">84</span></div></div>`, `    <Stat className="stat_row" card><span className="stat_icon-wrap color_success">✓</span><div className="stat_body"><span className="stat_label">완료</span><span className="stat_value">84</span></div></Stat>`, `  <Stat class="stat_row" card><span class="stat_icon-wrap color_success">✓</span><div class="stat_body"><span class="stat_label">완료</span><span class="stat_value">84</span></div></Stat>`),
  skins: stat('skins', `<div class="stat_group stat_group-3"><div class="stat stat_card">기본 카드</div><div class="stat stat_card stat_shadow">Shadow</div><div class="stat stat_card stat_borderless">Borderless</div></div>`, `    <div className="stat_group stat_group-3"><Stat card title="기본 카드" value="1,200" /><Stat card shadow title="Shadow" value="980" /><Stat card className="stat_borderless" title="Borderless" value="456" /></div>`, `  <div class="stat_group stat_group-3"><Stat card title="기본 카드" value="1,200" /><Stat card shadow title="Shadow" value="980" /><Stat card class="stat_borderless" title="Borderless" value="456" /></div>`),
  group: stat('group', `<div class="stat_group stat_group-4"><div class="stat stat_card"><span class="stat_label">총 매출</span><span class="stat_value">₩4.2M</span></div><div class="stat stat_card"><span class="stat_label">신규 가입</span><span class="stat_value">1,234</span></div></div>`, `    <div className="stat_group stat_group-4"><Stat card title="총 매출" value="₩4.2M" /><Stat card title="신규 가입" value="1,234" /></div>`, `  <div class="stat_group stat_group-4"><Stat card title="총 매출" value="₩4.2M" /><Stat card title="신규 가입" value="1,234" /></div>`)
};
