import type { FrameworkExample } from './FrameworkCode';
type Source = { html: string; react: string; vue: string };
const trigger = (id: string, label: string) => `<button class="btn btn_filled color_primary" data-drawer-trigger="#${id}" aria-controls="${id}">${label}</button>`;
const drawer = (id: string, title: string, body: string, panel = 'drawer_placement-right', attrs = '') => `<div id="${id}" class="drawer" data-drawer ${attrs} role="dialog" aria-modal="true" aria-labelledby="${id}-title" tabindex="-1" hidden>
  <div class="drawer_backdrop" data-drawer-close aria-hidden="true"></div>
  <div class="drawer_panel ${panel}"><div class="drawer_header"><h2 id="${id}-title" class="drawer_title">${title}</h2><button class="drawer_close" data-drawer-close aria-label="닫기">×</button></div><div class="drawer_body">${body}</div><div class="drawer_footer"><button class="btn btn_ghost" data-drawer-close>취소</button><button class="btn btn_filled color_primary" data-drawer-close>확인</button></div></div>
</div>`;
const sources: Record<string, Source> = {
  basic: { html: `${trigger('drawer-basic', 'Drawer 열기')}\n${drawer('drawer-basic', '상세 정보', '<p>Drawer 패널 본문입니다.</p>')}`, react: '<><Button label="Drawer 열기" onClick={() => setOpen(true)} /><Drawer open={open} title="상세 정보" onClose={() => setOpen(false)}><p>Drawer 패널 본문입니다.</p></Drawer></>', vue: '<Button label="Drawer 열기" @click="open = true" /><Drawer :open="open" title="상세 정보" @close="open = false"><p>Drawer 패널 본문입니다.</p></Drawer>' },
  open: { html: drawer('drawer-open', '알림', '<p>로드 시 열린 Drawer입니다.</p>').replace('class="drawer"', 'class="drawer is-open"').replace(' hidden', ''), react: '<Drawer defaultOpen title="알림"><p>로드 시 열린 Drawer입니다.</p></Drawer>', vue: '<Drawer default-open title="알림"><p>로드 시 열린 Drawer입니다.</p></Drawer>' },
  placement: { html: `${trigger('drawer-left', '왼쪽')}\n${drawer('drawer-left', '왼쪽 패널', '<p>왼쪽에서 열립니다.</p>', 'drawer_placement-left')}`, react: '<Drawer open={open} placement="left" title="왼쪽 패널" onClose={() => setOpen(false)} />', vue: '<Drawer :open="open" placement="left" title="왼쪽 패널" @close="open = false" />' },
  size: { html: drawer('drawer-lg', 'Large', '<p>넓은 패널</p>', 'drawer_panel drawer_placement-right drawer_lg').replace('drawer_panel drawer_panel', 'drawer_panel'), react: '<Drawer open={open} size="lg" title="Large" />', vue: '<Drawer :open="open" size="lg" title="Large" />' },
  footer: { html: `${trigger('drawer-footer', '항목 편집')}\n${drawer('drawer-footer', '항목 편집', '<label>이름 <input class="input"></label>')}`, react: '<Drawer open={open} title="항목 편집" footer={<><Button variant="ghost" label="취소" /><Button label="저장" /></>} />', vue: '<Drawer :open="open" title="항목 편집"><template #footer><Button variant="ghost" label="취소" /><Button label="저장" /></template></Drawer>' },
  footerAlign: { html: drawer('drawer-align', '푸터 정렬', '<p>균등 정렬</p>', 'drawer_placement-bottom').replace('drawer_footer"', 'drawer_footer drawer_footer-even"'), react: '<Drawer open={open} placement="bottom" footerAlign="even" footer={<><Button label="취소" /><Button label="확인" /></>} />', vue: '<Drawer :open="open" placement="bottom" footer-align="even"><template #footer><Button label="취소" /><Button label="확인" /></template></Drawer>' },
  extra: { html: drawer('drawer-extra', '주문 #1042', '<p>주문 상세 정보</p>').replace('<button class="drawer_close"', '<span class="tag">완료</span><button class="drawer_close"'), react: '<Drawer open title="주문 #1042" extra={<Tag>완료</Tag>} />', vue: '<Drawer open title="주문 #1042"><template #extra><Tag>완료</Tag></template></Drawer>' },
  menu: { html: `${trigger('drawer-menu', '메뉴 열기')}\n${drawer('drawer-menu', '앱 메뉴', '<nav class="menu"><a class="menu_link" href="#dashboard">대시보드</a></nav>', 'drawer_placement-left')}`, react: '<Drawer open={open} placement="left" title="앱 메뉴"><nav className="menu">대시보드 · 분석 · 설정</nav></Drawer>', vue: '<Drawer :open="open" placement="left" title="앱 메뉴"><nav class="menu">대시보드 · 분석 · 설정</nav></Drawer>' },
  nested: { html: `${trigger('drawer-parent', '첫 번째 Drawer 열기')}\n${drawer('drawer-parent', '첫 번째 Drawer', '<button data-drawer-trigger="#drawer-child">두 번째 열기</button>')}\n${drawer('drawer-child', '두 번째 Drawer', '<p>최상위 패널</p>', 'drawer_placement-right drawer_sm', 'style="--drawer-stack-level: 1"')}`, react: '<><Drawer open={parentOpen} title="첫 번째 Drawer" /><Drawer open={childOpen} size="sm" title="두 번째 Drawer" /></>', vue: '<Drawer :open="parentOpen" title="첫 번째 Drawer" /><Drawer :open="childOpen" size="sm" title="두 번째 Drawer" />' },
  dragSheet: { html: `${trigger('drawer-drag', '드래그 시트 열기')}\n${drawer('drawer-drag', '공유 · 액션', '<p>하단 액션 시트입니다.</p>', 'drawer_placement-bottom drawer_draggable', 'data-drawer-draggable="true"')}`, react: '<Drawer open={open} placement="bottom" draggable title="공유 · 액션"><p>하단 액션 시트입니다.</p></Drawer>', vue: '<Drawer :open="open" placement="bottom" draggable title="공유 · 액션"><p>하단 액션 시트입니다.</p></Drawer>' },
  noBackdrop: { html: drawer('drawer-plain', '백드롭 없음', '<p>패널만 표시합니다.</p>', 'drawer_placement-right drawer_sm', 'data-drawer-backdrop="false"'), react: '<Drawer open={open} noBackdrop size="sm" title="백드롭 없음" />', vue: '<Drawer :open="open" no-backdrop size="sm" title="백드롭 없음" />' },
};
const indent = (value: string, spaces: number) => value.split('\n').map((line) => `${' '.repeat(spaces)}${line}`).join('\n');
function examples(key: string, source: Source): FrameworkExample[] {
  const react = `import { useState } from 'react';\nimport Drawer from '@uxkm/react/drawer';\nimport Button from '@uxkm/react/button';\n\nexport function Example() {\n  const [open, setOpen] = useState(${key === 'open' ? 'true' : 'false'});\n  return (\n${indent(source.react, 4)}\n  );\n}`;
  const vue = `<script setup>\nimport { ref } from 'vue';\nimport Drawer from '@uxkm/vue/drawer';\nimport Button from '@uxkm/vue/button';\nconst open = ref(${key === 'open' ? 'true' : 'false'});\n</script>\n\n<template>\n${indent(source.vue, 2)}\n</template>`;
  return [{ id: 'html', label: 'HTML', fileName: `Drawer.html · ${key}`, code: source.html }, { id: 'gulp', label: 'Gulp', fileName: `drawer.njk · ${key}`, code: source.html }, { id: 'vue', label: 'Vue', fileName: `@uxkm/vue/drawer · ${key}`, code: vue }, { id: 'nuxt', label: 'Nuxt', fileName: `@uxkm/vue/drawer · ${key}`, code: vue }, { id: 'react', label: 'React', fileName: `@uxkm/react/drawer · ${key}`, code: react }, { id: 'next', label: 'Next', fileName: `@uxkm/react/drawer · ${key}`, code: react }];
}
export const drawerFrameworkExamples = Object.fromEntries(Object.entries(sources).map(([key, source]) => [key, examples(key, source)])) as Record<keyof typeof sources, FrameworkExample[]>;
