import type { FrameworkExample } from './FrameworkCode';
const names = ['basic','open','trigger','select','placement','menu','scroll','disabled','example'] as const;
type Name = (typeof names)[number];
const menuHtml = (labels: string[], active = '') => `<nav class="menu menu_vertical menu_compact" aria-label="메뉴"><ul class="menu_list">${labels.map((label) => `<li class="menu_item"><button type="button" class="menu_link${label === active ? ' is-active' : ''}"${label === active ? ' aria-current="page"' : ''}><span class="menu_label">${label}</span></button></li>`).join('')}</ul></nav>`;
const caret = '<svg class="icon" data-component="Icon" data-icon="chevron-down" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6"></path></svg>';
const htmlDropdown = (label: string, menu: string, options: { classes?: string; trigger?: string; style?: string; disabled?: boolean } = {}) => `<div class="dropdown${options.classes || ''}" data-component="Dropdown" data-dropdown><button type="button" class="btn ${options.trigger || 'btn_outline color_default'} dropdown_trigger" aria-haspopup="menu" aria-expanded="${options.classes?.includes('is-open') ? 'true' : 'false'}"${options.disabled ? ' disabled' : ''}><span class="btn_label">${label}</span>${caret}</button><div class="dropdown_menu${options.style ? ' dropdown_menu-scrollable' : ''}" role="menu" aria-hidden="${options.classes?.includes('is-open') ? 'false' : 'true'}"${options.style ? ` style="${options.style}"` : ''}>${menu}</div></div>`;
const html: Record<Name,string> = {
  basic: htmlDropdown('작업', menuHtml(['복사','이동','공유'])), open: htmlDropdown('카테고리', menuHtml(['전체','디자인','개발','마케팅'],'전체'), { classes:' is-open', trigger:'btn_filled color_primary' }),
  trigger: [htmlDropdown('Filled',menuHtml(['항목 1','항목 2']),{trigger:'btn_filled color_primary'}),htmlDropdown('Outline',menuHtml(['항목 1','항목 2'])),htmlDropdown('Ghost',menuHtml(['항목 1','항목 2']),{trigger:'btn_ghost color_default'}),htmlDropdown('Text',menuHtml(['항목 1','항목 2']),{trigger:'btn_text color_primary'}),htmlDropdown('더보기',menuHtml(['편집','복제','삭제']),{trigger:'btn_ghost color_default btn_icon-only'})].join('\n'),
  select: `${htmlDropdown('서울특별시',menuHtml(['서울특별시','부산광역시','대구광역시'],'서울특별시'),{classes:' dropdown_fit',trigger:'btn_select color_default'})}\n${htmlDropdown('최신순',menuHtml(['최신순','인기순','가격 낮은순'],'최신순'),{trigger:'btn_select btn_select-text color_default'})}`,
  placement: `${htmlDropdown('왼쪽 정렬',menuHtml(['항목 A','항목 B']))}\n${htmlDropdown('오른쪽 정렬',menuHtml(['항목 A','항목 B']),{classes:' dropdown_placement-end'})}\n${htmlDropdown('위로 열기',menuHtml(['위쪽 패널','항목 2']),{classes:' dropdown_placement-top'})}`,
  menu: htmlDropdown('계정', `<nav class="menu menu_vertical menu_compact" aria-label="계정 메뉴"><ul class="menu_list"><li class="menu_group"><span class="menu_group-title">계정</span></li><li class="menu_item"><button class="menu_link" type="button"><span class="menu_label">프로필</span></button></li><li class="menu_item"><button class="menu_link" type="button"><span class="menu_label">보안</span></button></li><li class="menu_divider" role="separator"></li><li class="menu_item"><button class="menu_link color_danger" type="button"><span class="menu_label">로그아웃</span></button></li></ul></nav>`,{classes:' is-open'}),
  scroll: `${htmlDropdown('도시 선택',menuHtml(['서울특별시','부산광역시','대구광역시','인천광역시','광주광역시','대전광역시','울산광역시']),{classes:' is-open',style:'--dropdown-max-visible-items: 4;'})}\n${htmlDropdown('넓은 패널',menuHtml(['프로젝트 대시보드','팀 협업 워크스페이스','문서 보관함 및 템플릿','알림 및 활동 기록','계정 및 보안 설정']),{classes:' is-open',style:'--dropdown-max-visible-items: 4; width: 18rem;'})}`,
  disabled: `${htmlDropdown('비활성 드롭다운',menuHtml(['항목']),{classes:' is-disabled',disabled:true})}\n${htmlDropdown('일부 비활성','<nav class="menu menu_vertical menu_compact"><ul class="menu_list"><li class="menu_item"><button class="menu_link" type="button"><span class="menu_label">조회</span></button></li><li class="menu_item"><button class="menu_link" type="button"><span class="menu_label">편집</span></button></li><li class="menu_item is-disabled"><span class="menu_link is-disabled" aria-disabled="true"><span class="menu_label">삭제</span></span></li><li class="menu_item is-disabled"><span class="menu_link is-disabled" aria-disabled="true"><span class="menu_label">관리자 설정</span></span></li></ul></nav>',{classes:' is-open'})}`,
  example: `<div class="dropdown_demo-toolbar"><button type="button" class="btn btn_ghost color_default btn_sm"><span class="btn_label">알림 <span class="badge badge_count badge_sm color_danger" data-component="Badge">2</span></span></button>${htmlDropdown('김가이드',menuHtml(['내 프로필','내 문서','로그아웃']),{classes:' dropdown_placement-end',trigger:'btn_ghost color_default btn_sm'})}</div>`,
};
const menuReact = (labels:string[], active='') => `<Menu compact>${labels.map((label)=>`<MenuItem label="${label}"${label===active?' active':''} />`).join('')}</Menu>`;
const ddReact = (label:string, menu:string, attrs='', trigger='variant="outline"') => `<Dropdown ${attrs} triggerContent={<Button ${trigger} label="${label}" iconAfter={<Icon name="chevron-down" />} />}>${menu}</Dropdown>`;
const react: Record<Name,string> = {
  basic:ddReact('작업',menuReact(['복사','이동','공유'])), open:ddReact('카테고리',menuReact(['전체','디자인','개발','마케팅'],'전체'),'open','variant="filled" color="primary"'),
  trigger:[ddReact('Filled',menuReact(['항목 1','항목 2']),'','variant="filled" color="primary"'),ddReact('Outline',menuReact(['항목 1','항목 2'])),ddReact('Ghost',menuReact(['항목 1','항목 2']),'','variant="ghost"'),ddReact('Text',menuReact(['항목 1','항목 2']),'','variant="text" color="primary"'),`<Dropdown triggerContent={<Button variant="ghost" iconOnly ariaLabel="더보기" iconBefore={<Icon name="menu" />} />}>${menuReact(['편집','복제','삭제'])}</Dropdown>`].join('\n'),
  select:`<Dropdown fit onSelect={setRegion} triggerContent={<Button variant="select" label={region} />}>${menuReact(['서울특별시','부산광역시','대구광역시'])}</Dropdown>\n<Dropdown onSelect={setSort} triggerContent={<Button variant="select" selectText label={sort} />}>${menuReact(['최신순','인기순','가격 낮은순'])}</Dropdown>`,
  placement:`${ddReact('왼쪽 정렬',menuReact(['항목 A','항목 B']))}\n${ddReact('오른쪽 정렬',menuReact(['항목 A','항목 B']),'placement="end"')}\n${ddReact('위로 열기',menuReact(['위쪽 패널','항목 2']),'placement="top"','variant="ghost"')}`,
  menu:`<Dropdown open triggerContent={<Button variant="outline" label="계정" iconAfter={<Icon name="chevron-down" />} />}><Menu compact><MenuGroup title="계정" /><MenuItem label="프로필" icon={<Icon name="user" className="menu_icon" />} /><MenuItem label="보안" icon={<Icon name="settings" className="menu_icon" />} /><MenuDivider /><MenuItem label="로그아웃" color="danger" /></Menu></Dropdown>`,
  scroll:`${ddReact('도시 선택',menuReact(['서울특별시','부산광역시','대구광역시','인천광역시','광주광역시','대전광역시']),'open maxVisibleItems={4}')}\n${ddReact('넓은 패널',menuReact(['프로젝트 대시보드','팀 협업 워크스페이스','문서 보관함 및 템플릿','알림 및 활동 기록','계정 및 보안 설정']),'open maxVisibleItems={4} menuWidth={18}')}`,
  disabled:`${ddReact('비활성 드롭다운',menuReact(['항목']),'disabled','variant="outline" disabled')}\n<Dropdown open triggerContent={<Button variant="outline" label="일부 비활성" /> }><Menu compact><MenuItem label="조회" /><MenuItem label="편집" /><MenuItem label="삭제" disabled /><MenuItem label="관리자 설정" disabled /></Menu></Dropdown>`,
  example:`<div className="dropdown_demo-toolbar"><Button variant="ghost" size="sm" iconBefore={<Icon name="bell" />}>알림 <Badge count size="sm" color="danger" label="2" /></Button><Dropdown placement="end" triggerContent={<Button variant="ghost" size="sm" iconAfter={<Icon name="chevron-down" />}><Avatar size="sm" color="primary" initials="김" ariaHidden /> 김가이드</Button>}>${menuReact(['내 프로필','내 문서','로그아웃'])}</Dropdown></div>`,
};
const menuVue = (labels:string[], active='') => `<Menu compact>${labels.map((label)=>`<MenuItem label="${label}"${label===active?' active':''} />`).join('')}</Menu>`;
const ddVue = (label:string, menu:string, attrs='', button='variant="outline"') => `<Dropdown ${attrs}><template #trigger="{ triggerProps }"><Button v-bind="triggerProps" ${button} label="${label}"><template #icon-after><Icon name="chevron-down" /></template></Button></template>${menu}</Dropdown>`;
const vue:Record<Name,string> = {
  basic:ddVue('작업',menuVue(['복사','이동','공유'])), open:ddVue('카테고리',menuVue(['전체','디자인','개발','마케팅'],'전체'),'open','variant="filled" color="primary"'),
  trigger:[ddVue('Filled',menuVue(['항목 1','항목 2']),'','variant="filled" color="primary"'),ddVue('Outline',menuVue(['항목 1','항목 2'])),ddVue('Ghost',menuVue(['항목 1','항목 2']),'','variant="ghost"'),ddVue('Text',menuVue(['항목 1','항목 2']),'','variant="text" color="primary"'),`<Dropdown><template #trigger="{ triggerProps }"><Button v-bind="triggerProps" variant="ghost" icon-only aria-label="더보기"><template #icon-before><Icon name="menu" /></template></Button></template>${menuVue(['편집','복제','삭제'])}</Dropdown>`].join('\n'),
  select:`<Dropdown fit @select="region = $event"><template #trigger="{ triggerProps }"><Button v-bind="triggerProps" variant="select" :label="region" /></template>${menuVue(['서울특별시','부산광역시','대구광역시'])}</Dropdown>\n<Dropdown @select="sort = $event"><template #trigger="{ triggerProps }"><Button v-bind="triggerProps" variant="select" select-text :label="sort" /></template>${menuVue(['최신순','인기순','가격 낮은순'])}</Dropdown>`,
  placement:`${ddVue('왼쪽 정렬',menuVue(['항목 A','항목 B']))}\n${ddVue('오른쪽 정렬',menuVue(['항목 A','항목 B']),'placement="end"')}\n${ddVue('위로 열기',menuVue(['위쪽 패널','항목 2']),'placement="top"','variant="ghost"')}`,
  menu:`<Dropdown open><template #trigger="{ triggerProps }"><Button v-bind="triggerProps" variant="outline" label="계정"><template #icon-after><Icon name="chevron-down" /></template></Button></template><Menu compact><MenuGroup title="계정" /><MenuItem label="프로필"><template #icon><Icon name="user" class="menu_icon" /></template></MenuItem><MenuItem label="보안"><template #icon><Icon name="settings" class="menu_icon" /></template></MenuItem><MenuDivider /><MenuItem label="로그아웃" color="danger" /></Menu></Dropdown>`,
  scroll:`${ddVue('도시 선택',menuVue(['서울특별시','부산광역시','대구광역시','인천광역시','광주광역시','대전광역시']),'open :max-visible-items="4"')}\n${ddVue('넓은 패널',menuVue(['프로젝트 대시보드','팀 협업 워크스페이스','문서 보관함 및 템플릿','알림 및 활동 기록','계정 및 보안 설정']),'open :max-visible-items="4" :menu-width="18"')}`,
  disabled:`${ddVue('비활성 드롭다운',menuVue(['항목']),'disabled','variant="outline" disabled')}\n<Dropdown open><template #trigger="{ triggerProps }"><Button v-bind="triggerProps" variant="outline" label="일부 비활성" /></template><Menu compact><MenuItem label="조회" /><MenuItem label="편집" /><MenuItem label="삭제" disabled /><MenuItem label="관리자 설정" disabled /></Menu></Dropdown>`,
  example:`<div class="dropdown_demo-toolbar"><Button variant="ghost" size="sm"><template #icon-before><Icon name="bell" /></template>알림 <Badge count size="sm" color="danger" label="2" /></Button><Dropdown placement="end"><template #trigger="{ triggerProps }"><Button v-bind="triggerProps" variant="ghost" size="sm"><Avatar size="sm" color="primary" initials="김" aria-hidden /> 김가이드<template #icon-after><Icon name="chevron-down" /></template></Button></template>${menuVue(['내 프로필','내 문서','로그아웃'])}</Dropdown></div>`,
};
function examples(key:Name):FrameworkExample[]{ const needsState=key==='select'; const reactCode=`${needsState?"import { useState } from 'react';\n":''}import Dropdown from '@uxkm/react/dropdown';\nimport Button from '@uxkm/react/button';\nimport Icon from '@uxkm/react/icon';\nimport { Menu, MenuItem, MenuGroup, MenuDivider } from '@uxkm/react/menu';${key==='example'?"\nimport Avatar from '@uxkm/react/avatar';\nimport Badge from '@uxkm/react/badge';":''}\n\nexport function Example(){ ${needsState?"const [region,setRegion]=useState('서울특별시'); const [sort,setSort]=useState('최신순'); ":''}return <>${react[key]}</>; }`; const vueCode=`<script setup>\n${needsState?"import { ref } from 'vue';\n":''}import Dropdown from '@uxkm/vue/dropdown';\nimport Button from '@uxkm/vue/button';\nimport Icon from '@uxkm/vue/icon';\nimport { Menu, MenuItem, MenuGroup, MenuDivider } from '@uxkm/vue/menu';${key==='example'?"\nimport Avatar from '@uxkm/vue/avatar';\nimport Badge from '@uxkm/vue/badge';":''}${needsState?"\nconst region=ref('서울특별시'); const sort=ref('최신순');":''}\n</script>\n<template>\n${vue[key]}\n</template>`; return [{id:'html',label:'HTML',fileName:`Dropdown.html · ${key}`,code:html[key]},{id:'gulp',label:'Gulp',fileName:`dropdown.njk · ${key}`,code:html[key]},{id:'vue',label:'Vue',fileName:`@uxkm/vue/dropdown · ${key}`,code:vueCode},{id:'nuxt',label:'Nuxt',fileName:`@uxkm/vue/dropdown · ${key}`,code:vueCode},{id:'react',label:'React',fileName:`@uxkm/react/dropdown · ${key}`,code:reactCode},{id:'next',label:'Next',fileName:`@uxkm/react/dropdown · ${key}`,code:reactCode}]; }
export const dropdownFrameworkExamples=Object.fromEntries(names.map((key)=>[key,examples(key)])) as Record<Name,FrameworkExample[]>;
