import { useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import ActualPopover from '../../react/src/components/feedback/Popover/Popover.jsx';
import ActualButton from '../../react/src/components/basic/Button/Button.jsx';
import ActualLink from '../../react/src/components/basic/Link/Link.jsx';
import ActualIcon from '../../react/src/components/basic/Icon/Icon.jsx';
import ActualTextarea from '../../react/src/components/form/Textarea/Textarea.jsx';

const Popover = ActualPopover as React.ComponentType<any>;
const Button = ActualButton as React.ComponentType<any>;
const Link = ActualLink as React.ComponentType<any>;
const Icon = ActualIcon as React.ComponentType<any>;
const Textarea = ActualTextarea as React.ComponentType<any>;

function Demo({ label = 'Popover 열기', initialOpen = false, triggerContent, footer, children, buttonProps, ...props }: any) {
  const [open, setOpen] = useState(initialOpen);
  const actions = footer ? <><Button variant="ghost" size="sm" label={footer.cancel || '취소'} onClick={() => setOpen(false)} /><Button variant="filled" color={footer.color || 'primary'} size="sm" label={footer.confirm || '확인'} onClick={() => setOpen(false)} /></> : undefined;
  return <Popover {...props} open={open} onOpenChange={setOpen} triggerContent={triggerContent ?? <Button className="popover_trigger" variant="outline" label={label} {...buttonProps} />} footer={actions}>{children}</Popover>;
}

const meta = { title: '피드백/Popover', component: Popover, decorators: [(Story) => <div className="popover-story-demo"><Story /></div>], parameters: { layout: 'padded' }, argTypes: { placement: { control: 'select', options: ['top', 'top-center', 'bottom', 'bottom-center', 'left', 'right', 'end'] }, size: { control: 'select', options: ['sm', 'md', 'lg'] }, trigger: { control: 'select', options: ['click', 'hover'] } } } satisfies Meta<typeof Popover>;
export default meta;
type Story = StoryObj<typeof meta>;

export const Basic: Story = { name: '기본', render: () => <Demo panelLabel="안내"><p>트리거를 클릭하면 이 패널이 표시됩니다.</p></Demo> };
export const NoLabel: Story = { name: '라벨 없음', render: () => <Demo label="라벨 없음"><p>짧은 안내 문구만 필요할 때 사용합니다. 제목 행 없이 콘텐츠가 바로 표시됩니다.</p></Demo> };
export const Open: Story = { name: '열린 상태', render: () => <Demo initialOpen panelLabel="열린 Popover" label="열림" buttonProps={{ variant: 'filled', color: 'primary' }}><p>정적 데모용 열린 상태입니다.</p></Demo> };

export const Size: Story = { name: '크기', render: () => <div className="popover_row" style={{ alignItems: 'flex-start' }}><Demo size="sm" panelLabel="작은 Popover" label="Small" buttonProps={{ size: 'sm' }}><p>작은 패널입니다. 짧은 안내에 적합합니다.</p></Demo><Demo panelLabel="기본 Popover" label="Medium"><p>기본 크기 패널입니다.</p></Demo><Demo size="lg" panelLabel="큰 Popover" label="Large" buttonProps={{ size: 'lg' }}><p>큰 패널입니다. 본문이 길거나 폼·목록을 담을 때 사용합니다.</p></Demo></div> };

export const Offset: Story = { name: '간격', render: () => <div className="popover_demo-stage"><p className="form_field-hint">전 방향 동일</p><div className="popover_row"><Demo offset="none" panelLabel="none" label="none" buttonProps={{ size: 'sm' }}><p>간격 없음</p></Demo><Demo offset="sm" panelLabel="sm" label="sm" buttonProps={{ size: 'sm' }}><p>좁은 간격</p></Demo><Demo panelLabel="md" label="md" buttonProps={{ size: 'sm' }}><p>기본 간격</p></Demo><Demo offset="lg" panelLabel="lg" label="lg" buttonProps={{ size: 'sm' }}><p>넓은 간격</p></Demo></div><p className="form_field-hint" style={{ marginTop: 'var(--space-lg)' }}>방향별 (offset-* · placement)</p><div className="popover_demo-placement" style={{ minHeight: '12rem', padding: 0 }}><div className="popover_demo-placement-cell-top"><Demo placement="top-center" offsetTop="lg" panelLabel="offset-top lg" label="위" buttonProps={{ size: 'sm' }}><p>위쪽 간격</p></Demo></div><div className="popover_demo-placement-cell-left"><Demo placement="left" offsetLeft="lg" panelLabel="offset-left lg" label="왼쪽" buttonProps={{ size: 'sm' }}><p>왼쪽 간격</p></Demo></div><div className="popover_demo-placement-cell-center"><Demo offsetBottom="lg" panelLabel="offset-bottom lg" label="아래" buttonProps={{ size: 'sm' }}><p>아래쪽 간격</p></Demo></div><div className="popover_demo-placement-cell-right"><Demo placement="right" offsetRight="lg" panelLabel="offset-right lg" label="오른쪽" buttonProps={{ size: 'sm' }}><p>오른쪽 간격</p></Demo></div></div></div> };

export const Title: Story = { name: '제목', render: () => <Demo title="배송 안내" label="도움말" buttonProps={{ variant: 'ghost' }}><p>평일 오후 2시 이전 주문은 당일 출고됩니다. 제주·도서 산간 지역은 1~2일 추가 소요될 수 있습니다.</p></Demo> };
export const Footer: Story = { name: '푸터', render: () => <Demo title="항목 삭제" label="삭제 확인" footer={{ cancel: '취소', confirm: '삭제', color: 'danger' }}><p>이 작업은 되돌릴 수 없습니다. 계속하시겠습니까?</p></Demo> };
export const Hover: Story = { name: '호버 트리거', render: () => <p>결제 시{' '}<Demo trigger="hover" closable={false} panelLabel="에스크로 설명" triggerContent={<Link className="popover_trigger" label="에스크로" />}>구매자가 상품 수령을 확인할 때까지 대금을 안전하게 보관하는 결제 방식입니다.</Demo>{' '}서비스를 이용할 수 있습니다.</p> };
export const Trigger: Story = { name: '트리거 유형', render: () => <div className="popover_row"><Demo panelLabel="Button 트리거" label="Button" buttonProps={{ variant: 'filled', color: 'primary' }}><p>버튼 트리거 예시입니다.</p></Demo><Demo panelLabel="Link 트리거" triggerContent={<Link className="popover_trigger" label="Link 트리거" />}><p>링크 스타일 트리거입니다.</p></Demo><Demo panelLabel="추가 정보" triggerContent={<Button className="popover_trigger" variant="ghost" iconOnly ariaLabel="정보" iconBefore={<Icon name="info" />} />}><p>아이콘 전용 트리거입니다.</p></Demo></div> };

export const Placement: Story = { name: '배치', render: () => <div className="popover_demo-stage"><div className="popover_demo-placement"><div className="popover_demo-placement-cell-top"><Demo placement="top-center" panelLabel="위쪽 가운데 배치" label="위" buttonProps={{ size: 'sm' }}><p>트리거 위 · 가운데</p></Demo></div><div className="popover_demo-placement-cell-left"><Demo placement="left" panelLabel="왼쪽 배치" label="왼쪽" buttonProps={{ size: 'sm' }}><p>트리거 왼쪽</p></Demo></div><div className="popover_demo-placement-cell-center"><Demo placement="bottom-center" panelLabel="아래쪽 가운데 배치" label="아래" buttonProps={{ size: 'sm' }}><p>트리거 아래 · 가운데</p></Demo></div><div className="popover_demo-placement-cell-right"><Demo placement="right" panelLabel="오른쪽 배치" label="오른쪽" buttonProps={{ size: 'sm' }}><p>트리거 오른쪽</p></Demo></div></div><div className="popover_row" style={{ width: '100%', justifyContent: 'space-between', marginTop: 'var(--space-xl)' }}><Demo placement="top" panelLabel="위쪽 왼쪽 정렬" label="위 · 왼쪽 정렬" buttonProps={{ variant: 'ghost' }}><p>패널 왼쪽 정렬</p></Demo><Demo panelLabel="아래쪽 왼쪽 정렬" label="아래 · 왼쪽 정렬" buttonProps={{ variant: 'ghost' }}><p>기본 배치</p></Demo><Demo placement="end" panelLabel="오른쪽 정렬" label="아래 · 오른쪽 정렬" buttonProps={{ variant: 'ghost' }}><p>패널 오른쪽 정렬</p></Demo></div></div> };

export const Form: Story = { name: '폼', render: () => <Demo title="빠른 메모" label="메모 추가" footer={{ cancel: '취소', confirm: '저장' }}><div className="form_field"><label className="form_label" htmlFor="popover-memo-input">내용</label><Textarea id="popover-memo-input" rows={3} placeholder="메모를 입력하세요" /></div></Demo> };

const ArrowDemo = ({ panelAlign = 'start', arrowTargetAlign = 'center', label, children, arrowAnchor = 'mixed' }: any) => <Demo arrowAnchor={arrowAnchor} panelAlign={panelAlign} arrowTargetAlign={arrowTargetAlign} panelLabel={label} label="S" buttonProps={{ size: 'sm' }}>{children}</Demo>;
const MixedArrowRows = () => <><p className="form_field-hint" style={{ marginTop: 'var(--space-lg)' }}>mixed — 패널 왼쪽 · 화살표 조합</p><div className="popover_row"><ArrowDemo panelAlign="start" arrowTargetAlign="left" label="왼쪽 · ←"><p>패널 왼쪽 정렬, 화살표 왼쪽.</p></ArrowDemo><ArrowDemo panelAlign="start" label="왼쪽 · ●"><p>패널 왼쪽, 화살표 가운데.</p></ArrowDemo><ArrowDemo panelAlign="start" arrowTargetAlign="right" label="왼쪽 · →"><p>패널 왼쪽, 화살표 오른쪽.</p></ArrowDemo></div><p className="form_field-hint" style={{ marginTop: 'var(--space-lg)' }}>mixed — 패널 오른쪽 · 화살표 조합</p><div className="popover_row"><ArrowDemo panelAlign="end" arrowTargetAlign="left" label="오른쪽 · ←"><p>패널 오른쪽 정렬, 화살표 왼쪽.</p></ArrowDemo><ArrowDemo panelAlign="end" label="오른쪽 · ●"><p>패널 오른쪽, 화살표 가운데.</p></ArrowDemo><ArrowDemo panelAlign="end" arrowTargetAlign="right" label="오른쪽 · →"><p>패널 오른쪽, 화살표 오른쪽.</p></ArrowDemo></div></>;
export const ArrowAnchor: Story = { name: '화살표 기준', render: () => <div className="popover_demo-stage"><p className="form_field-hint">기준 비교</p><div className="popover_row"><ArrowDemo arrowAnchor="content" label="content"><p>패널이 트리거보다 넓을 때 화살표는 패널 패딩 기준으로 배치됩니다.</p></ArrowDemo><ArrowDemo arrowAnchor="target" label="target"><p>패널이 트리거보다 넓을 때 화살표가 트리거 중앙을 가리킵니다.</p></ArrowDemo></div><p className="form_field-hint" style={{ marginTop: 'var(--space-lg)' }}>target — 좌 · 가운데 · 우</p><div className="popover_row"><ArrowDemo arrowAnchor="target" arrowTargetAlign="left" label="left"><p>트리거 왼쪽을 가리킵니다.</p></ArrowDemo><ArrowDemo arrowAnchor="target" label="center"><p>트리거 가운데를 가리킵니다.</p></ArrowDemo><ArrowDemo arrowAnchor="target" arrowTargetAlign="right" label="right"><p>트리거 오른쪽을 가리킵니다.</p></ArrowDemo></div><p className="form_field-hint" style={{ marginTop: 'var(--space-lg)' }}>mixed — 패널 가운데 · 화살표 조합</p><div className="popover_row"><ArrowDemo panelAlign="center" arrowTargetAlign="left" label="가운데 · ←"><p>패널 가운데, 화살표 트리거 왼쪽.</p></ArrowDemo><ArrowDemo panelAlign="center" label="가운데 · ●"><p>패널·화살표 모두 트리거 가운데.</p></ArrowDemo><ArrowDemo panelAlign="center" arrowTargetAlign="right" label="가운데 · →"><p>패널 가운데, 화살표 트리거 오른쪽.</p></ArrowDemo></div><MixedArrowRows /></div> };

export const NoArrow: Story = { name: '화살표 없음', render: () => <Demo noArrow panelLabel="화살표 없는 Popover" label="화살표 없음" buttonProps={{ variant: 'ghost' }}><p>화살표가 표시되지 않는 패널입니다.</p></Demo> };
