import type { ApiColumn, ApiRow, ApiSectionData } from './shared/ComponentApiDocs';
const columns: ApiColumn[] = [{ key: 'name', label: '이름' }, { key: 'description', label: '설명' }, { key: 'default', label: '기본값' }, { key: 'type', label: '타입' }];
const section = (title: string, rows: ApiRow[], description?: string): ApiSectionData => ({ title, description, tables: [{ columns, rows }] });
export const progressApiSections: ApiSectionData[] = [
  section('React · Next.js API', [{ name: 'percent', type: 'number', default: '0', description: '0~100 진행률입니다.' }, { name: 'status', type: "'' | 'success' | 'exception'", default: "''", description: '완료·예외 상태 색상입니다.' }, { name: 'size · color', type: 'string', default: "'md' · 'primary'", description: '크기와 의미 색상입니다.' }, { name: 'showInfo · label', type: 'boolean · string', default: 'false · —', description: '상단 레이블과 값을 표시합니다.' }, { name: 'striped · animated · indeterminate · inside · block', type: 'boolean', default: 'false', description: '패턴, 애니메이션, 불확정, 내부 값, 전체 너비 옵션입니다.' }, { name: 'ariaLabel', type: 'string', default: "'진행률'", description: '접근성 이름입니다.' }], 'Next.js는 @uxkm/react/progress를 재사용합니다.'),
  section('ProgressCircle API', [{ name: 'percent · color · size · ariaLabel', type: 'number · string', default: "0 · 'primary' · 'md' · '진행률'", description: '원형 진행률 값과 표현 옵션입니다.' }]),
  section('Vue · Nuxt API', [{ name: 'percent · status · size · color', type: 'number · string', default: "0 · '' · 'md' · 'primary'", description: '진행률과 표현 상태입니다.' }, { name: 'show-info · striped · animated · indeterminate · inside · block', type: 'boolean', default: 'false', description: '선형 진행률 표시 옵션입니다.' }], 'Nuxt는 @uxkm/vue/progress를 재사용합니다.'),
  section('HTML · Gulp', [{ name: 'progress · progress_track · progress_bar', type: 'class', default: '—', description: '루트, 트랙, 채움 막대입니다.' }, { name: 'role · aria-valuenow/min/max', type: 'attribute', default: '—', description: '진행률 접근성 속성입니다.' }]),
  section('디자인 토큰', [{ name: '--progress-height · --progress-max-width', type: 'length', default: '8px · input-max-width', description: '선형 진행률 높이와 최대 너비입니다.' }, { name: '--progress-circle-size · --progress-circle-stroke', type: 'length · number', default: '7.5rem · 6', description: '원형 진행률 크기와 선 두께입니다.' }]),
];
