import type { ApiColumn, ApiRow, ApiSectionData } from './shared/ComponentApiDocs';
const columns: ApiColumn[] = [{ key: 'name', label: '이름' }, { key: 'description', label: '설명' }, { key: 'default', label: '기본값' }, { key: 'type', label: '타입' }];
const section = (title: string, rows: ApiRow[]): ApiSectionData => ({ title, tables: [{ columns, rows }] });
export const stepsApiSections: ApiSectionData[] = [
  section('Steps API', [{ name: 'current · v-model:current', type: 'number', default: '—', description: '상태를 자동 계산할 때 사용하는 현재 단계입니다.' }, { name: 'direction', type: "'horizontal' | 'vertical'", default: "'horizontal'", description: '단계 배치 방향입니다.' }, { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: '인디케이터와 텍스트 크기입니다.' }, { name: 'dot · iconStyle', type: 'boolean', default: 'false', description: '도트 및 아이콘 인디케이터 변형입니다.' }, { name: 'navigable', type: 'boolean', default: 'false', description: '완료된 단계를 클릭해 이전 단계로 이동합니다.' }, { name: 'align', type: "'' | 'center'", default: "''", description: '가로 단계의 콘텐츠 정렬입니다.' }, { name: 'onChange · change', type: '(step) => void', default: '—', description: '탐색 가능한 단계 변경 이벤트입니다.' }, { name: 'items · children · default slot', type: 'StepData[] · ReactNode · slot', default: '[]', description: '단계 항목입니다.' }]),
  section('StepsItem API', [{ name: 'title · #title', type: 'string · ReactNode · slot', default: '—', description: '단계 제목 콘텐츠입니다.' }, { name: 'description · #description', type: 'string · ReactNode · slot', default: '—', description: '보조 설명 콘텐츠입니다.' }, { name: 'status', type: "'finished' | 'active' | 'wait' | 'error'", default: "'wait'", description: '단계의 진행 상태입니다.' }, { name: 'icon · #icon', type: 'ReactNode · slot', default: '상태 아이콘/번호', description: '사용자가 교체할 수 있는 인디케이터 콘텐츠입니다.' }, { name: 'completeIcon · errorIcon', type: 'ReactNode', default: 'Icon check · close', description: 'React 완료 및 오류 아이콘을 교체합니다.' }]),
  section('HTML · Gulp', [{ name: 'data-steps · data-step-index', type: 'attribute', default: '—', description: '탐색 가능한 단계 동작과 순서를 연결합니다.' }, { name: 'steps:change', type: 'CustomEvent', default: '—', description: '변경된 current를 detail로 전달합니다.' }, { name: 'is-finished · is-active · is-wait · is-error', type: 'class', default: '—', description: '완료, 현재, 대기, 오류 상태 클래스입니다.' }]),
  section('디자인 토큰', [{ name: '--steps-indicator-size', type: 'length', default: '2rem', description: '인디케이터 크기입니다.' }, { name: '--steps-gap · --steps-head-gap', type: 'length', default: 'space-md · space-sm', description: '단계와 헤더 요소 간격입니다.' }, { name: '--steps-title-size · --steps-desc-size', type: 'length', default: 'text-size-sm · text-size-xs', description: '제목과 설명 크기입니다.' }]),
];
